### PR TITLE
translate to ENGLISH README and put Chinese README in another file

### PR DESCRIPTION
**Pull request by cutebear0123**
translate to ENGLISH README and put Chinese README in another file

- [x] i put the url for your repositories so you do not need change after merge

### CODE REVIEW

**Comment by ItzMiracleOwO** [comment]
Hi there, thank you for the PR, but we will prefer putting the chinese README in the Readme.md and put the english version in other file, since the project is facing the chinese community. The file will be added after this merge! Thank u again!

**Comment by cutebear0123** [comment]
.W.

**Comment by cutebear0123** [comment]
you forget put the url in the zh readme

**Comment by ItzMiracleOwO** [comment]
lol will put

**Pull request merged**
